### ISSUE TITLE
First row is hidden by table header in ST 2.4.2

### ISSUE THREAD

**Issue by Eli-Thomas** [mitchellsimoens/Ext.ux.touch.grid#56]
For the reason that lower version of  ST is not working properly in Chrome 43+,  I update my ST to 2.4.2. After updating my app, I found that   Ext.ux.touch.grid come  with a bug:  the first row is hidden by table header and start  show data from row 2 . The First row can only show temporary  by scrolling  down  the table. 
Can you offer any  fixed for this bug?

**Comment by mitchellsimoens** [comment]
The last time I worked on this repo (minus an example update) was 2 years ago. Since I work for Sencha and we now have a touch grid within the framework (not part of the commercial/gpl release, part of the bundle) I decided not to compete with myself. Therefore, I will not be working on this but you (and anyone else) are more than welcome to submit a pull request.

**Comment by Eli-Thomas** [comment]
Oops.  It is more likely a bug of ST 2.4.2.  I suppose it is  also a bug in the Ext.dataview.ListView come with a toolbar or even for a fit-layout container with toolbar. Can you give any hint or suggest for this bug ?

**Comment by mitchellsimoens** [comment]
I do not support Sencha Touch here. Please open a thread in the Sencha forums with a standalone test case (via Sencha Fiddle) that reproduces the issue you have found.

**Comment by Eli-Thomas** [comment]
Fixed the bug by adding   "position: Relative" in Ext.ux.grid.List.css:

``` javascript
.touchgridpanel .x-grid-header {
    padding : 0;
    position: Relative; 
}
```

In ST 2.4.2 , the deafult property of  position in  .x-grid-header  somehow has been changed  to  absolute; 
By adding this line,  Ext.ux.grid.List can run perfectly in the ST 2.4.2 and older version of ST.

Thanks to @mitchellsimoens.
